# This file is auto-generated. DO NOT MODIFY!

# The following files are removed due to issues:
#
# build/src/libultra/os/timerintr.o: BSS reordering of the OSThread structs due to presumed order.
# build/src/libultra/libc/llcvt.o: Calls functions expected to be loaded before code gets loaded, which means
# must be placed in boot. However boot has shifting instability so this is not possible yet.
# build/src/libultra/libc/ll.o: Same issue as llcvt.o.


SAFE_C_FILES :=    \
    build/src/overlays/gamestates/ovl_select/z_select.o    \
    build/src/overlays/gamestates/ovl_opening/z_opening.o    \
    build/src/overlays/gamestates/ovl_title/z_title.o    \
    build/src/overlays/gamestates/ovl_daytelop/z_daytelop.o    \
    build/src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.o    \
    build/src/overlays/actors/ovl_Bg_Keikoku_Spr/z_bg_keikoku_spr.o    \
    build/src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.o    \
    build/src/overlays/actors/ovl_En_Po_Fusen/z_en_po_fusen.o    \
    build/src/overlays/actors/ovl_Arms_Hook/z_arms_hook.o    \
    build/src/overlays/actors/ovl_En_Bji_01/z_en_bji_01.o    \
    build/src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.o    \
    build/src/overlays/actors/ovl_En_Ending_Hero/z_en_ending_hero.o    \
    build/src/overlays/actors/ovl_Bg_Lbfshot/z_bg_lbfshot.o    \
    build/src/overlays/actors/ovl_En_Torch2/z_en_torch2.o    \
    build/src/overlays/actors/ovl_En_Ending_Hero6/z_en_ending_hero6.o    \
    build/src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.o    \
    build/src/overlays/actors/ovl_En_Nnh/z_en_nnh.o    \
    build/src/overlays/actors/ovl_Bg_Fu_Kaiten/z_bg_fu_kaiten.o    \
    build/src/overlays/actors/ovl_Obj_Boyo/z_obj_boyo.o    \
    build/src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.o    \
    build/src/overlays/actors/ovl_En_Poh/z_en_poh.o    \
    build/src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.o    \
    build/src/overlays/actors/ovl_Dm_Nb/z_dm_nb.o    \
    build/src/overlays/actors/ovl_Door_Spiral/z_door_spiral.o    \
    build/src/overlays/actors/ovl_En_Mm/z_en_mm.o    \
    build/src/overlays/actors/ovl_Dm_Ravine/z_dm_ravine.o    \
    build/src/overlays/actors/ovl_Obj_Milk_Bin/z_obj_milk_bin.o    \
    build/src/overlays/actors/ovl_En_Scopecoin/z_en_scopecoin.o    \
    build/src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.o    \
    build/src/overlays/actors/ovl_En_Cow/z_en_cow.o    \
    build/src/overlays/actors/ovl_En_Wf/z_en_wf.o    \
    build/src/overlays/actors/ovl_En_Fg/z_en_fg.o    \
    build/src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.o    \
    build/src/overlays/actors/ovl_En_Holl/z_en_holl.o    \
    build/src/overlays/actors/ovl_En_Suttari/z_en_suttari.o    \
    build/src/overlays/actors/ovl_Obj_Kibako2/z_obj_kibako2.o    \
    build/src/overlays/actors/ovl_Bg_Iknin_Susceil/z_bg_iknin_susceil.o    \
    build/src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.o    \
    build/src/overlays/actors/ovl_En_Ot/z_en_ot.o    \
    build/src/overlays/actors/ovl_Bg_Kin2_Fence/z_bg_kin2_fence.o    \
    build/src/overlays/actors/ovl_En_Elforg/z_en_elforg.o    \
    build/src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.o    \
    build/src/overlays/actors/ovl_Obj_Hana/z_obj_hana.o    \
    build/src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.o    \
    build/src/overlays/actors/ovl_Bg_Ikana_Shutter/z_bg_ikana_shutter.o    \
    build/src/overlays/actors/ovl_En_Firefly/z_en_firefly.o    \
    build/src/overlays/actors/ovl_Obj_Etcetera/z_obj_etcetera.o    \
    build/src/overlays/actors/ovl_En_Tag_Obj/z_en_tag_obj.o    \
    build/src/overlays/actors/ovl_En_Baguo/z_en_baguo.o    \
    build/src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.o    \
    build/src/overlays/actors/ovl_En_Owl/z_en_owl.o    \
    build/src/overlays/actors/ovl_En_Dai/z_en_dai.o    \
    build/src/overlays/actors/ovl_Obj_Funen/z_obj_funen.o    \
    build/src/overlays/actors/ovl_Bg_Haka_Tomb/z_bg_haka_tomb.o    \
    build/src/overlays/actors/ovl_Bg_Iknv_Obj/z_bg_iknv_obj.o    \
    build/src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.o    \
    build/src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.o    \
    build/src/overlays/actors/ovl_En_Dnp/z_en_dnp.o    \
    build/src/overlays/actors/ovl_En_Kgy/z_en_kgy.o    \
    build/src/overlays/actors/ovl_Dm_Stk/z_dm_stk.o    \
    build/src/overlays/actors/ovl_En_Fu/z_en_fu.o    \
    build/src/overlays/actors/ovl_Obj_Lightblock/z_obj_lightblock.o    \
    build/src/overlays/actors/ovl_En_Ma4/z_en_ma4.o    \
    build/src/overlays/actors/ovl_En_Firefly2/z_en_firefly2.o    \
    build/src/overlays/actors/ovl_En_Guruguru/z_en_guruguru.o    \
    build/src/overlays/actors/ovl_En_Tk/z_en_tk.o    \
    build/src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.o    \
    build/src/overlays/actors/ovl_En_Zl1/z_en_zl1.o    \
    build/src/overlays/actors/ovl_Item_Inbox/z_item_inbox.o    \
    build/src/overlays/actors/ovl_En_Encount2/z_en_encount2.o    \
    build/src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.o    \
    build/src/overlays/actors/ovl_En_Dnb/z_en_dnb.o    \
    build/src/overlays/actors/ovl_En_Tite/z_en_tite.o    \
    build/src/overlays/actors/ovl_En_Fish2/z_en_fish2.o    \
    build/src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.o    \
    build/src/overlays/actors/ovl_En_In/z_en_in.o    \
    build/src/overlays/actors/ovl_En_Ending_Hero5/z_en_ending_hero5.o    \
    build/src/overlays/actors/ovl_Obj_Kibako/z_obj_kibako.o    \
    build/src/overlays/actors/ovl_Obj_Tokei_Step/z_obj_tokei_step.o    \
    build/src/overlays/actors/ovl_En_Dno/z_en_dno.o    \
    build/src/overlays/actors/ovl_En_Boj_03/z_en_boj_03.o    \
    build/src/overlays/actors/ovl_En_Fr/z_en_fr.o    \
    build/src/overlays/actors/ovl_En_Tanron6/z_en_tanron6.o    \
    build/src/overlays/actors/ovl_Bg_Ctower_Rot/z_bg_ctower_rot.o    \
    build/src/overlays/actors/ovl_Bg_Tobira01/z_bg_tobira01.o    \
    build/src/overlays/actors/ovl_En_Dnk/z_en_dnk.o    \
    build/src/overlays/actors/ovl_En_Gm/z_en_gm.o    \
    build/src/overlays/actors/ovl_En_Sw/z_en_sw.o    \
    build/src/overlays/actors/ovl_En_Rsn/z_en_rsn.o    \
    build/src/overlays/actors/ovl_En_M_Fire1/z_en_m_fire1.o    \
    build/src/overlays/actors/ovl_Obj_Visiblock/z_obj_visiblock.o    \
    build/src/overlays/actors/ovl_Bg_Haka_Curtain/z_bg_haka_curtain.o    \
    build/src/overlays/actors/ovl_En_Ossan/z_en_ossan.o    \
    build/src/overlays/actors/ovl_En_Ma_Yts/z_en_ma_yts.o    \
    build/src/overlays/actors/ovl_En_Fire_Rock/z_en_fire_rock.o    \
    build/src/overlays/actors/ovl_En_Pm/z_en_pm.o    \
    build/src/overlays/actors/ovl_Eff_Dust/z_eff_dust.o    \
    build/src/overlays/actors/ovl_En_Hit_Tag/z_en_hit_tag.o    \
    build/src/overlays/actors/ovl_En_Jc_Mato/z_en_jc_mato.o    \
    build/src/overlays/actors/ovl_En_Boj_01/z_en_boj_01.o    \
    build/src/overlays/actors/ovl_En_Cha/z_en_cha.o    \
    build/src/overlays/actors/ovl_En_Boj_05/z_en_boj_05.o    \
    build/src/overlays/actors/ovl_Item_B_Heart/z_item_b_heart.o    \
    build/src/overlays/actors/ovl_Obj_Aqua/z_obj_aqua.o    \
    build/src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.o    \
    build/src/overlays/actors/ovl_Bg_Ctower_Gear/z_bg_ctower_gear.o    \
    build/src/overlays/actors/ovl_Dm_Char07/z_dm_char07.o    \
    build/src/overlays/actors/ovl_En_Muto/z_en_muto.o    \
    build/src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.o    \
    build/src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.o    \
    build/src/overlays/actors/ovl_En_Hg/z_en_hg.o    \
    build/src/overlays/actors/ovl_Bg_Mbar_Chair/z_bg_mbar_chair.o    \
    build/src/overlays/actors/ovl_Arrow_Ice/z_arrow_ice.o    \
    build/src/overlays/actors/ovl_En_Minislime/z_en_minislime.o    \
    build/src/overlays/actors/ovl_En_Trt/z_en_trt.o    \
    build/src/overlays/actors/ovl_En_Ending_Hero3/z_en_ending_hero3.o    \
    build/src/overlays/actors/ovl_En_Ending_Hero2/z_en_ending_hero2.o    \
    build/src/overlays/actors/ovl_Obj_Ghaka/z_obj_ghaka.o    \
    build/src/overlays/actors/ovl_En_Baisen/z_en_baisen.o    \
    build/src/overlays/actors/ovl_Dm_Sa/z_dm_sa.o    \
    build/src/overlays/actors/ovl_En_Bu/z_en_bu.o    \
    build/src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.o    \
    build/src/overlays/actors/ovl_Obj_Ending/z_obj_ending.o    \
    build/src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.o    \
    build/src/overlays/actors/ovl_Obj_Kepn_Koya/z_obj_kepn_koya.o    \
    build/src/overlays/actors/ovl_En_Rr/z_en_rr.o    \
    build/src/overlays/actors/ovl_En_Torch/z_en_torch.o    \
    build/src/overlays/actors/ovl_Obj_Bell/z_obj_bell.o    \
    build/src/overlays/actors/ovl_Bg_Icicle/z_bg_icicle.o    \
    build/src/overlays/actors/ovl_Obj_Mu_Pict/z_obj_mu_pict.o    \
    build/src/overlays/actors/ovl_En_Hs2/z_en_hs2.o    \
    build/src/overlays/actors/ovl_En_Rd/z_en_rd.o    \
    build/src/overlays/actors/ovl_En_Warp_Uzu/z_en_warp_uzu.o    \
    build/src/overlays/actors/ovl_En_Skb/z_en_skb.o    \
    build/src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.o    \
    build/src/overlays/actors/ovl_En_Boj_04/z_en_boj_04.o    \
    build/src/overlays/actors/ovl_En_Tubo_Trap/z_en_tubo_trap.o    \
    build/src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.o    \
    build/src/overlays/actors/ovl_En_Sb/z_en_sb.o    \
    build/src/overlays/actors/ovl_Obj_Mure/z_obj_mure.o    \
    build/src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.o    \
    build/src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.o    \
    build/src/overlays/actors/ovl_Bg_Ladder/z_bg_ladder.o    \
    build/src/overlays/actors/ovl_Door_Ana/z_door_ana.o    \
    build/src/overlays/actors/ovl_Dm_Statue/z_dm_statue.o    \
    build/src/overlays/actors/ovl_Demo_Shd/z_demo_shd.o    \
    build/src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.o    \
    build/src/overlays/actors/ovl_En_Floormas/z_en_floormas.o    \
    build/src/overlays/actors/ovl_En_Fsn/z_en_fsn.o    \
    build/src/overlays/actors/ovl_En_Sob1/z_en_sob1.o    \
    build/src/overlays/actors/ovl_En_Dnq/z_en_dnq.o    \
    build/src/overlays/actors/ovl_En_Test4/z_en_test4.o    \
    build/src/overlays/actors/ovl_En_Dns/z_en_dns.o    \
    build/src/overlays/actors/ovl_Bg_Ikana_Ray/z_bg_ikana_ray.o    \
    build/src/overlays/actors/ovl_En_Zot/z_en_zot.o    \
    build/src/overlays/actors/ovl_Obj_Hgdoor/z_obj_hgdoor.o    \
    build/src/overlays/actors/ovl_Obj_Makeoshihiki/z_obj_makeoshihiki.o    \
    build/src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.o    \
    build/src/overlays/actors/ovl_Obj_Moon_Stone/z_obj_moon_stone.o    \
    build/src/overlays/actors/ovl_En_Pamera/z_en_pamera.o    \
    build/src/overlays/actors/ovl_En_Ginko_Man/z_en_ginko_man.o    \
    build/src/overlays/actors/ovl_En_Daiku2/z_en_daiku2.o    \
    build/src/overlays/actors/ovl_Obj_HsStump/z_obj_hsstump.o    \
    build/src/overlays/actors/ovl_En_Niw/z_en_niw.o    \
    build/src/overlays/actors/ovl_Boss_02/z_boss_02.o    \
    build/src/overlays/actors/ovl_En_Giant/z_en_giant.o    \
    build/src/overlays/actors/ovl_En_Boj_02/z_en_boj_02.o    \
    build/src/overlays/actors/ovl_En_Dg/z_en_dg.o    \
    build/src/overlays/actors/ovl_Obj_Warpstone/z_obj_warpstone.o    \
    build/src/overlays/actors/ovl_Bg_Market_Step/z_bg_market_step.o    \
    build/src/overlays/actors/ovl_En_Ending_Hero4/z_en_ending_hero4.o    \
    build/src/overlays/actors/ovl_En_Stream/z_en_stream.o    \
    build/src/overlays/actors/ovl_Obj_Dinner/z_obj_dinner.o    \
    build/src/overlays/actors/ovl_En_Elfbub/z_en_elfbub.o    \
    build/src/overlays/actors/ovl_TG_Sw/z_tg_sw.o    \
    build/src/overlays/actors/ovl_En_Daiku/z_en_daiku.o    \
    build/src/overlays/actors/ovl_En_Toto/z_en_toto.o    \
    build/src/overlays/actors/ovl_En_GirlA/z_en_girla.o    \
    build/src/boot_O2_g3/yaz0.o    \
    build/src/boot_O2_g3/boot_main.o    \
    build/src/boot_O2_g3/z_std_dma.o    \
    build/src/boot_O2_g3/idle_extra_bss.o    \
    build/src/boot_O2_g3/viconfig.o    \
    build/src/boot_O2_g3/syncprintf.o    \
    build/src/boot_O2_g3/idle.o    \
    build/src/boot_O2_g3/build.o    \
    build/src/boot_O2_g3/irqmgr.o    \
    build/src/boot_O2_g3/fault.o    \
    build/src/boot_O2_g3/CIC6105.o    \
    build/src/libultra/libc/ldiv.o    \
    build/src/libultra/libc/string.o    \
    build/src/libultra/gu/ortho.o    \
    build/src/libultra/gu/perspective.o    \
    build/src/libultra/gu/lookat.o    \
    build/src/libultra/gu/position.o    \
    build/src/libultra/gu/cosf.o    \
    build/src/libultra/gu/sinf.o    \
    build/src/libultra/gu/rotate.o    \
    build/src/libultra/gu/guS2DInitBg.o    \
    build/src/libultra/gu/sins.o    \
    build/src/libultra/gu/lookathil.o    \
    build/src/libultra/gu/coss.o    \
    build/src/libultra/gu/visetevent.o    \
    build/src/libultra/gu/sqrtf.o    \
    build/src/libultra/flash/osFlash.o    \
    build/src/libultra/io/sirawdma.o    \
    build/src/libultra/io/piacs.o    \
    build/src/libultra/io/dpgetstat.o    \
    build/src/libultra/io/vimgr.o    \
    build/src/libultra/io/dpsetstat.o    \
    build/src/libultra/io/crc.o    \
    build/src/libultra/io/sirawwrite.o    \
    build/src/libultra/io/osViModeNtscHpf1.o    \
    build/src/libultra/io/pimgr.o    \
    build/src/libultra/io/aigetlen.o    \
    build/src/libultra/io/contpfs.o    \
    build/src/libultra/io/contquery.o    \
    build/src/libultra/io/osViModeNtscLan1.o    \
    build/src/libultra/io/epilinkhandle.o    \
    build/src/libultra/io/cartrominit.o    \
    build/src/libultra/io/controller.o    \
    build/src/libultra/io/spgetstat.o    \
    build/src/libultra/io/osViModeMpalLan1.o    \
    build/src/libultra/io/viswapbuf.o    \
    build/src/libultra/io/sptask.o    \
    build/src/libultra/io/pirawdma.o    \
    build/src/libultra/io/vi.o    \
    build/src/libultra/io/epidma.o    \
    build/src/libultra/io/visetyscale.o    \
    build/src/libultra/io/osViModePalLan1.o    \
    build/src/libultra/io/pfsfilestate.o    \
    build/src/libultra/io/epirawread.o    \
    build/src/libultra/io/pfsallocatefile.o    \
    build/src/libultra/io/epirawdma.o    \
    build/src/libultra/io/sp.o    \
    build/src/libultra/io/sprawdma.o    \
    build/src/libultra/io/sirawread.o    \
    build/src/libultra/io/pfsinitpak.o    \
    build/src/libultra/io/aisetfreq.o    \
    build/src/libultra/io/visetspecial.o    \
    build/src/libultra/io/visetmode.o    \
    build/src/libultra/io/vigetcurrcontext.o    \
    build/src/libultra/io/spsetstat.o    \
    build/src/libultra/io/vigetnextframebuf.o    \
    build/src/libultra/io/contsetch.o    \
    build/src/libultra/io/devmgr.o    \
    build/src/libultra/io/epiwrite.o    \
    build/src/libultra/io/pfsisplug.o    \
    build/src/libultra/io/pfschecker.o    \
    build/src/libultra/io/motor.o    \
    build/src/libultra/io/sptaskyield.o    \
    build/src/libultra/io/contreaddata.o    \
    build/src/libultra/io/epirawwrite.o    \
    build/src/libultra/io/spsetpc.o    \
    build/src/libultra/io/vigetcurrframebuf.o    \
    build/src/libultra/io/viblack.o    \
    build/src/libultra/io/pfsselectbank.o    \
    build/src/libultra/io/pfsdeletefile.o    \
    build/src/libultra/io/si.o    \
    build/src/libultra/io/visetxscale.o    \
    build/src/libultra/io/siacs.o    \
    build/src/libultra/io/pfssearchfile.o    \
    build/src/libultra/io/epiread.o    \
    build/src/libultra/io/pigetcmdq.o    \
    build/src/libultra/io/sptaskyielded.o    \
    build/src/libultra/voice/voicecrc.o    \
    build/src/libultra/voice/voicegetstatus.o    \
    build/src/libultra/os/settime.o    \
    build/src/libultra/os/destroythread.o    \
    build/src/libultra/os/startthread.o    \
    build/src/libultra/os/getcurrfaultthread.o    \
    build/src/libultra/os/gettime.o    \
    build/src/libultra/os/settimer.o    \
    build/src/libultra/os/setthreadpri.o    \
    build/src/libultra/os/setglobalintmask.o    \
    build/src/libultra/os/createthread.o    \
    build/src/libultra/os/getthreadid.o    \
    build/src/libultra/os/yieldthread.o    \
    build/src/libultra/os/getthreadpri.o    \
    build/src/libultra/os/getactivequeue.o    \
    build/src/libultra/os/threadsave.o    \
    build/src/libultra/os/virtualtophysical.o    \
    build/src/libultra/os/sethwinterrupt.o    \
    build/src/libultra/os/initialize.o    \
    build/src/libultra/os/viextend.o    \
    build/src/libultra/os/createmesgqueue.o    \
    build/src/libultra/os/thread.o    \
    build/src/libultra/os/stoptimer.o    \
    build/src/libultra/os/gethwinterrupt.o    \
    build/src/libultra/os/sendmesg.o    \
    build/src/libultra/os/recvmesg.o    \
    build/src/libultra/os/resetglobalintmask.o    \
    build/src/libultra/os/stopthread.o    \
    build/src/libultra/os/jammesg.o    \
    build/src/libultra/os/afterprenmi.o    \
    build/src/libultra/os/getmemsize.o    \
    build/src/libultra/os/seteventmesg.o    \
    build/src/libultra/rmon/xprintf.o    \
    build/src/libultra/rmon/xlitob.o    \
    build/src/libultra/rmon/sprintf.o    \
    build/src/libultra/rmon/xldtob.o    \
    build/src/boot_O2/__osStrcpy.o    \
    build/src/boot_O2/boot_80086760.o    \
    build/src/boot_O2/__osMemcpy.o    \
    build/src/boot_O2/rand.o    \
    build/src/boot_O2/padsetup.o    \
    build/src/boot_O2/stackcheck.o    \
    build/src/boot_O2/boot_80084940.o    \
    build/src/boot_O2/__osMemset.o    \
    build/src/boot_O2/sleep.o    \
    build/src/boot_O2/printutils.o    \
    build/src/boot_O2/mtxuty-cvt.o    \
    build/src/boot_O2/assert.o    \
    build/src/boot_O2/padutils.o    \
    build/src/boot_O2/__osStrcmp.o    \
    build/src/boot_O2/fmodf.o    \
    build/src/boot_O2/loadfragment2.o    \
    build/src/boot_O2/system_malloc.o    \
    build/src/buffers/heaps.o    \
    build/src/buffers/gfxbuffers.o    \
    build/src/code/z_nmi_buff.o    \
    build/src/code/z_bg_collect.o    \
    build/src/code/z_scene.o    \
    build/src/code/game.o    \
    build/src/code/z_jpeg.o    \
    build/src/code/z_snap.o    \
    build/src/code/z_shrink_window.o    \
    build/src/code/z_kanfont.o    \
    build/src/code/z_lights.o    \
    build/src/code/z_bgcheck.o    \
    build/src/code/z_collision_check.o    \
    build/src/code/z_fcurve_data_skelanime.o    \
    build/src/code/sys_initial_check.o    \
    build/src/code/sys_math_atan.o    \
    build/src/code/z_skelanime.o    \
    build/src/code/z_construct.o    \
    build/src/code/code_800E8EA0.o    \
    build/src/code/z_common_data.o    \
    build/src/code/z_effect_soft_sprite.o    \
    build/src/code/z_face_reaction.o    \
    build/src/code/sys_slowly.o    \
    build/src/code/title_setup.o    \
    build/src/code/z_actor_dlftbls.o    \
    build/src/code/code_8010C1B0.o    \
    build/src/code/audioMgr.o    \
    build/src/code/graphalloc.o    \
    build/src/code/z_scene_table.o    \
    build/src/code/z_elf_message.o    \
    build/src/code/z_en_a_keep.o    \
    build/src/code/TwoHeadArena.o    \
    build/src/code/z_collision_btltbls.o    \
    build/src/code/sched.o    \
    build/src/code/z_skin_matrix.o    \
    build/src/code/z_path.o    \
    build/src/code/pad_801DC9C0.o    \
    build/src/code/TwoHeadGfxArena.o    \
    build/src/code/graph.o    \
    build/src/code/z_fireobj.o    \
    build/src/code/z_debug.o    \
    build/src/code/z_en_item00.o    \
    build/src/code/z_scene_proc.o    \
    build/src/code/gamealloc.o    \
    build/src/code/jpegdecoder.o    \
    build/src/code/z_view.o    \
    build/src/code/z_lifemeter.o    \
    build/src/code/listalloc.o    \
    build/src/code/z_olib.o    \
    build/src/code/z_game_dlftbls.o    \
    build/src/code/z_eff_footmark.o    \
    build/src/code/z_game_over.o    \
    build/src/code/z_env_flags.o    \
    build/src/code/z_effect.o    \
    build/src/code/code_80183070.o    \
    build/src/code/z_bg_item.o    \
    build/src/code/z_quake.o    \
    build/src/code/jpegutils.o    \
    build/src/code/z_prenmi.o    \
    build/src/code/z_rcp.o    \
    build/src/code/z_malloc.o    \
    build/src/code/z_effect_soft_sprite_old_init.o    \
    build/src/code/z_vr_box_draw.o    \
    build/src/code/flg_set.o    \
    build/src/code/main.o    \
    build/src/code/sys_math.o    \
    build/src/code/z_lib.o    \
    build/src/code/audio/audio_sfx_params.o    \
